### ISSUE TITLE
custom metric problem

### ISSUE THREAD

**Issue by persontu1** [wwoods/keras_pickle_wrapper#5]
I've stored a keras model  using a custom auc metric, but when i restore it from other processes the intepreter raised an error:
ValueError: Unknown metric function:auc
It seems that the metric wasn't stored along with the model
some help might be useful, thanks

**Comment by wwoods** [comment]
Hi, sorry for the delay.

Are you using `KerasPickleWrapper.register(your_auc_fn)` before saving or loading your model?  The way Keras serializes objects requires custom classes (and functions) to be registered.

**Comment by oras903** [comment]
hi ,  when  I  wrap the keras model ,  cross_val_score across multiprocessing     is still  getting error    **can't pickle _thread.lock objects**

how can i solve this ? thanks
